env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - '@typescript-eslint'
  - react
rules: {
  react/no-multi-comp: error,
  react/prefer-es6-class: true,
  react/prefer-stateless-function: true,
  react/jsx-closing-bracket-location: true,
  react/jsx-closing-tag-location: true,
}
